services:
  grafana:
    image: grafana/grafana
    restart: unless-stopped
    volumes:
      - ./configs/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafana-storage:/var/lib/grafana
    networks:
      - default
    ports:
      - 3000:3000 #WebUI

  prometheus:
    image: prom/prometheus
    command: ["--config.file=/etc/prometheus/prometheus.yml"]
    restart: unless-stopped
    volumes:
      - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - default
    ports:
      - 9090:9090 #WebUI

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    restart: unless-stopped
    volumes:
      - ./configs/otel/config.yaml:/etc/otelcol-contrib/config.yaml
    networks:
      - default
    ports:
      - 4317:4317 # OTLP gRPC receiver
      - 8888:8888 # Prometheus metrics exposed by the collector
      - 8889:8889 # Prometheus exporter metrics

  ngrok:
    image: ngrok/ngrok
    command: ["http", "http://otel-collector:4317", "--url=${NGROK_DOMAIN}", "--host-header=${NGROK_DOMAIN}", "--upstream-protocol=http2"]
    restart: unless-stopped
    environment:
      - NGROK_AUTHTOKEN="${NGROK_AUTHTOKEN}"
    networks:
      - default
    ports:
      - 4040:4040 # WebUI

volumes:
  grafana-storage:
  prometheus-data:

networks:
  default:
